# Trabajando con arrays en múltiples dimensiones

Toca tener un poco de teoría esta vez antes de poner las manos en la masa.
Cuando trabajamos con conjuntos de datos, estos pueden estar organizados en distintas dimensiones.

* **Escalar/Scalar**: cuando su dimensión es 0. Por ejemplo, un `int` o un `float` son escalares. Solo tienen una componente, que es la magnitud que representan.
* **Vector/Vector**: Cuando su dimensión es 1. Por ejemplo, la colección `[1, 2, 3, 4, 5]` es un vector, ya que solo se mueve en una dirección.
* **Matriz/Matrix**: Cuando su dimensión es 2 o 3. Por ejemplo, la colección
 ```python
 [[1, 2, 3,],
 [1, 2, 3],
 [1, 2, 3]]
 ```
 Sería una matriz de dos dimensiones, mientras que una de tres sería de esta forma:
 ```python
 [
    [[1, 2, 3,], [1, 2, 3]],
    [[1, 2, 3,], [1, 2, 3]],
    [[1, 2, 3,], [1, 2, 3]]
 ]
 ```
* **Tensor/Tensor**: Cuando su dimensión es superior a 3. Aunque no se pueden representar gráficamente, en Python se verían algo así:
 ```python
 [
   [
      [[1, 2, 3,], [1, 2, 3]], 
      [[1, 2, 3], [1, 2, 3]]
   ],
   [
      [[1, 2, 3,], [1, 2, 3]], 
      [[1, 2, 3], [1, 2, 3]]
   ],
   [
      [[1, 2, 3,], [1, 2, 3]], 
      [[1, 2, 3], [1, 2, 3]]
   ],
 ]
 ```

Una vez con la teoría lista, pasemos a Numpy.

In [2]:
import numpy as np

In [5]:
scalar = np.array(10)
print(scalar)
print(scalar.ndim)

10
0


**Hey!** Con `np.array.ndim ` se puede visualizar la dimensión de un objeto.

In [6]:
vector = np.array([x for x in range(1, 6)])
print(vector)
print(vector.ndim)

[1 2 3 4 5]
1


In [9]:
matrix_2d = np.array([[x for x in range(0, 3)] for y in range(0, 3)])
print(matrix_2d)
print(matrix_2d.ndim)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
2


In [3]:
matrix_3d = np.array([[[x for x in range(0, 3)] for y in range(0, 3)] for z in range(0, 3)])
print(matrix_3d)
print(matrix_3d.ndim)

[[[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
3


In [4]:
tensor = np.array([[[[x for x in range(0, 3)] for y in range(0, 3)] for z in range(0, 3)] for u in range(0, 3)])
print(tensor)
print(tensor.ndim)

[[[[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]]


 [[[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]]


 [[[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]]]
4


# Agregar o quitar dimensiones

Con `np.expand_dims(array, axis)` añadimos más dimensiones al array.

In [15]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

Y con `np.squeeze` Numpy busca la dimensión que debería tener el array.

In [18]:
reduce = np.squeeze(expand)
print(reduce)
reduce.ndim

[1 2 3]


1

Ahora, usemos el tensor de antes para practicar un poco esto.

In [8]:
expanded_tensor = np.expand_dims(tensor, axis=0)
print(expanded_tensor)
expanded_tensor.ndim

[[[[[0 1 2]
    [0 1 2]
    [0 1 2]]

   [[0 1 2]
    [0 1 2]
    [0 1 2]]

   [[0 1 2]
    [0 1 2]
    [0 1 2]]]


  [[[0 1 2]
    [0 1 2]
    [0 1 2]]

   [[0 1 2]
    [0 1 2]
    [0 1 2]]

   [[0 1 2]
    [0 1 2]
    [0 1 2]]]


  [[[0 1 2]
    [0 1 2]
    [0 1 2]]

   [[0 1 2]
    [0 1 2]
    [0 1 2]]

   [[0 1 2]
    [0 1 2]
    [0 1 2]]]]]


5

In [9]:
reduced_tensor = np.squeeze(tensor)
print(reduced_tensor)
reduced_tensor.ndim

[[[[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]]


 [[[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]]


 [[[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]

  [[0 1 2]
   [0 1 2]
   [0 1 2]]]]


4