# Haciendo preguntas sobre los arrays

Empecemos con lo de siempre.

In [1]:
import numpy as np

Declaremos un array.

In [7]:
arr = np.linspace(1, 10, 10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

Probemos buscando los elementos mayores que 5.

In [18]:
greater_than_5 = arr > 5
greater_than_5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Esto nos devuelve una lista que nos dice si cada elemento de ``arr`` cumple con la condición. Además, podemos usar esta sintaxis para obtener directamente los elementos que cumplen con la condición.

In [19]:
arr[greater_than_5]

array([ 6,  7,  8,  9, 10], dtype=int8)

O, equivalentemente:

In [20]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10], dtype=int8)

Obviamente, también se pueden concatenar condiciones. En este caso, hay que encapsular cada evaluación entre paréntesis.

In [25]:
arr[(arr > 3) & (arr < 8)]

array([4, 5, 6, 7], dtype=int8)

Incluso, si quisiéramos, podríamos modificar los valores que cumplan con la condición que hemos impuesto.

In [26]:
arr[(arr > 3) & (arr < 8)] = 0
arr

array([ 1,  2,  3,  0,  0,  0,  0,  8,  9, 10], dtype=int8)

In [27]:
arr[arr == 0]

array([0, 0, 0, 0], dtype=int8)