# Operando con arrays

In [1]:
import numpy as np

## Operaciones aritméticas básicas.

Supongamos que queremos multiplicar por dos los elementos de una lista. Empecemos por declararla:

In [2]:
list_arr = [1, 2]

[1, 2, 1, 2]

In [3]:
list_arr * 2

[1, 2, 1, 2]

Pero, esto no los multiplicó por dos, sino que los duplicó. Esto es porque Python interpreta que la operación a realizar es una multiplicación. Veamos qué sucede si lo hacemos desde Numpy.

In [9]:
arr = np.arange(0, 10)
arr_copy = arr.copy()
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr_copy * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Probemos a hacer un par más de operaciones.

In [11]:
arr_copy + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
arr_copy / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

## Y qué pasa si tengo una división entre 0?

In [13]:
1 / arr

C:\Users\reari\AppData\Local\Temp\ipykernel_17880\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

Cuando encontró un 0, en vez de lanzar un error, ejecutó un warning sin detener la ejecución del script. Esto lo hace muy poderoso a la hora de trabajar con grandes conjuntos de datos.

También, podemos encadenar varias operaciones entre sí.

## Encadenando operaciones

In [16]:
(arr_copy * 3) + (arr_copy - 2)

array([-2,  2,  6, 10, 14, 18, 22, 26, 30, 34])

## Operando con cosas distintas a arrays con una dimensión

Todo esto que hemos visto, también funciona con matrices, tensores, y bueno, todo lo demás.

In [19]:
matrix = arr.reshape(2, 5)
matrix_copy = matrix.copy()
matrix_copy

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
matrix * matrix_copy - 2

array([[-2, -1,  2,  7, 14],
       [23, 34, 47, 62, 79]])

In [21]:
matrix - matrix_copy

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## Producto punto

Incluso, podríamos hacer el producto punto. Esto hay dos formas de hacerlo:

In [22]:
np.matmul(matrix, matrix_copy.T)

array([[ 30,  80],
       [ 80, 255]])

In [24]:
matrix @ matrix_copy.T

array([[ 30,  80],
       [ 80, 255]])

Particularmente, creo que es más clara la sintaxis np.matmul, ya que el arroba (``@``) es usado también para los decoradores, y puede no ser clara la operación que hace.