# Haciendo referencias y editando objetos con ``ndarray.copy``.

Antes de ver la función de este método, veamos por qué quisiéramos algo así. Ejecutemos algo de código.

In [1]:
import numpy as np

## Planteando el problema

Aquí, creamos un array cualquiera.

In [2]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Luego instanciamos una variable haciendo referencia al array, en este caso, las primeras 6 posiciones.

In [4]:
arr_slice = arr[:6]
arr_slice

array([0, 1, 2, 3, 4, 5])

Luego, supongamos que queramos poner todas las posiciones de este nuevo array a cero.

In [6]:
arr_slice[:] = 0
arr_slice

array([0, 0, 0, 0, 0, 0])

Perfecto. Ahora, queremos volver a acceder al array original. Veamos qué contiene.

In [7]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

## Entendiendo el problema

Se borró todo. Esto es porque cuando hacemos ``arr_slice = arr[:6]``, ``arr_slice`` hace referencia a ``arr``, y no a sus valores. Por lo tanto, cada vez que modificamos algo de ``arr_slice``, Numpy se va al valor que refiere, que es ``arr``, y lo modifica.

## Solucionando el problema

Para evitar esto, hacemos una *shallow copy*, que es un nuevo objeto que contiene referencias a los valores de ``arr``, y que es independiente de ``arr``. Veamos esto, pero antes, restablezcamos el valor de ``arr``:

In [23]:
arr = np.arange(0, 11)

Ahora, ejecutemos el código anterior, pero esta vez usando ``arr.copy``.

In [24]:
arr_slice = arr[:6].copy()
arr_slice[:] = 0
print("arr_slice:", arr_slice)
print("arr:", arr)

arr_slice: [0 0 0 0 0 0]
arr: [ 0  1  2  3  4  5  6  7  8  9 10]


Ahora, dejamos intacto ``arr``, y solo modificamos los valores de ``arr_slice``.