# El array

In [1]:
import numpy as np

In [3]:
lista = [x for x in range(1, 10)]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Para llevarlo a Numpy, usamos:

In [7]:
np_list = np.array(lista)

In [8]:
type(np_list)

numpy.ndarray

# Yyyy, matrices?
Al toque mi rey:

In [11]:
matrix = [[x for x in range(0, 3)] for y in range(0, 3)]
matrix

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]

Hey, esta forma de generar matrices es interesante. Básicamente, anidando list comprehension en list comprehension.

In [12]:
np_matrix = np.array(matrix)
np_matrix

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

# Indexing
(o acceder a los elementos)

In [17]:
print(np_list)
print(f"np_list[0]: {np_list[0]}")
print('*'*20)
print(np_matrix)
print(f"np_matrix[1]: {np_matrix[1]}")
print(f"np_matrix[0, 2]: {np_matrix[0, 2]}")

[1 2 3 4 5 6 7 8 9]
np_list[0]: 1
********************
[[0 1 2]
 [0 1 2]
 [0 1 2]]
np_matrix[1]: [0 1 2]
np_matrix[0, 2]: 2
