# Creando arrays

Pero antes de todo, lo más importante en esta fiesta:

In [1]:
import numpy as np

Con podemos generar una array similar a la lista que generamos con `list(range(0, 10))`

In [4]:
print(list(range(0, 10)))
np.arange(0, 10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

La diferencia entre `np.arrange(0, 10)` y `list(range(0, 10))` es que `np.arange` es más eficiente en términos de memoria y procesador a la hora de hacer operaciones sobre el conjunto. Por eso, usamos Numpy frente a los objetos built-in de Python a la hora de trabajar con grandes conjuntos de datos.

## np.zeros

`np.zeros(dims_tuple)` crea un array vacío con las dimensiones indicadas en `dims_tuple`. Esto es útil a la hora de crear placeholders, que usaremos para construir cosas, idk.

Por ejemplo, aquí crearé un array vacío 3x3:

In [9]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Y aquí un 3x3x3:

In [10]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

Y ya que estamos, un 3x3x3x3x3:

In [11]:
np.zeros((3, 3, 3, 3, 3))

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]],



       [[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
    

(creo que eso ya fue pasarse)

No siempre tienen que ser ceros. También pueden ser unos. Estos los creamos con

## np.ones

La sintaxis es la misma, checa:

In [12]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones((3, 3, 2, 3))

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

## np.linspace

Con esta cosa hacemos un array (de una dimensión) con números uniformemente espaciados dentro de un intervalo específico (no lo digo yo, lo dice la documentación: https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

Aquí, vamos a crear un array del 1 al 10, con 20 pasos:

In [16]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

A partir de Numpy 1.16.0, podemos usar no-escalares para hacer estas colecciones. Aquí, empezarían a tener dimensiones superiores a 1, como en este ejemplo:

In [21]:
vector = np.linspace((0, 1), (1, 2), 5)
print(vector)
vector.ndim

[[0.   1.  ]
 [0.25 1.25]
 [0.5  1.5 ]
 [0.75 1.75]
 [1.   2.  ]]


2

In [27]:
vector = np.linspace(((0, 0), (1, 1)), ((1, 1), (2, 2)), 5)
print(vector)
vector.ndim

[[[0.   0.  ]
  [1.   1.  ]]

 [[0.25 0.25]
  [1.25 1.25]]

 [[0.5  0.5 ]
  [1.5  1.5 ]]

 [[0.75 0.75]
  [1.75 1.75]]

 [[1.   1.  ]
  [2.   2.  ]]]


3

## np.eye(n)

Esta cosa crea una matriz identidad de `n` dimensiones:

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## np.random.rand(n)

Esta otra cosa crea un flotante aleatorio entre 0 y 1. También, le puedes indicar el número de dimensiones.

In [30]:
scalar = np.random.rand()  # Por defecto, es dimensión 1.
scalar

0.6032472452533061

In [33]:
vector = np.random.rand(5)
vector

array([0.71297521, 0.49588694, 0.5260356 , 0.04980001, 0.56527447])

In [36]:
matrix = np.random.rand(2, 2)
matrix

array([[0.60524707, 0.24266337],
       [0.65362944, 0.50003418]])

In [37]:
matrix_3d = np.random.rand(2, 2, 2)
matrix_3d

array([[[0.91274239, 0.41052284],
        [0.90681802, 0.17067326]],

       [[0.74122762, 0.66152303],
        [0.67401775, 0.34094378]]])

También, podemos crear arrays con enteros. Para esto usamos:

## np.random.randint

In [40]:
int_scalar = np.random.randint(1, 5)
int_scalar

3

In [45]:
int_vector = np.random.randint(1, 10, (10))
int_vector

array([9, 4, 2, 8, 9, 8, 4, 3, 6, 5])

In [47]:
int_matrix = np.random.randint(1, 20, (3, 3))
int_matrix

array([[ 8,  2,  3],
       [ 9,  1,  7],
       [14,  7, 18]])