# Principales funciones de Numpy

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 20, 10)
matrix = arr.reshape(2, 5)
matrix

array([[ 9,  3,  7,  4, 10],
       [ 4,  1,  5,  8,  7]])

## ``ndarray.max``

``ndarray.max`` devuelve el elemento más grande de un array.

In [3]:
matrix.max()

10

### Indicando la componente a buscar

Esto lo hacemos pasando como parámetro el índice de la dimensión a buscar.

Por ejemplo, si quisiéramos ver los valor máximo de las columnas:

In [4]:
matrix.max(0)

array([ 9,  3,  7,  8, 10])

Y los valores máximos de las filas:

In [5]:
matrix.max(1)

array([10,  8])

## ``ndarray.argmax``

``argmax`` indica la posición del elemento más grande. Del mismo modo que ``max``, le podemos indicar en qué dimensión buscarlo.

In [6]:
arr.argmax()

4

In [7]:
matrix.argmax(0)

array([0, 0, 0, 1, 0], dtype=int64)

## ``ndarray.min``

No me voy a extender acá, simplemente es la misma sintaxis de ``max``, solo que te busca el mínimo. También existe un ``argmin``.

In [8]:
matrix.min()

1

In [9]:
matrix.min(1)

array([3, 1])

In [10]:
matrix.argmin(0)

array([1, 1, 1, 0, 1], dtype=int64)

## ``ndarray.ptp``

``ptp`` son las siglas de Peak to Peak, o pico a pico. Lo que hace es indicar la distancia (en valor, no en posiciones) entre el valor más grande del array y el más pequeño.

In [11]:
matrix

array([[ 9,  3,  7,  4, 10],
       [ 4,  1,  5,  8,  7]])

In [12]:
matrix.ptp(0)

array([5, 2, 2, 4, 3])

Como vemos, en la primera posición hay un 6. Esto es porque el valor más pequeño de esa columna, 3, está 6 unidades de distancia del 9. Así con los demás elementos.

## ``np.percentile(ndarray, percentile)``

Esta función nos indica el valor del percentil de un array.

In [13]:
arr

array([ 9,  3,  7,  4, 10,  4,  1,  5,  8,  7])

In [14]:
np.percentile(arr, 50)

6.0

In [15]:
np.percentile(arr, 100)

10.0

## ``ndarray.sort``

Este método nos permite ordenar un array.

In [16]:
print("arr before sorting:", arr)
arr.sort()
print("arr after sorting:", arr)

arr before sorting: [ 9  3  7  4 10  4  1  5  8  7]
arr after sorting: [ 1  3  4  4  5  7  7  8  9 10]


In [17]:
print("matrix before sorting:\n", matrix)
matrix.sort()
print("matrix after sorting:\n", matrix)

matrix before sorting:
 [[ 1  3  4  4  5]
 [ 7  7  8  9 10]]
matrix after sorting:
 [[ 1  3  4  4  5]
 [ 7  7  8  9 10]]


## ``np.median(ndarray)``

Esta función nos devuelve la mediana de un conjunto.

In [18]:
np.median(arr)

6.0

In [19]:
np.median(matrix)

6.0

También le podemos indicar por cuál eje tomar los valores para calcular la mediana, en el caso de que el array no sea de una sola dimensión:

In [21]:
np.median(matrix, 1)

array([4., 8.])

## ``np.std(ndarray)``

Esta función nos devuelve la desviación estándar de un conjunto. Del mismo modo que ``np.median``, podemos indicarle el eje por el cuál va a tomar los datos la función.

In [22]:
np.std(arr)

2.7129319932501073

In [23]:
np.std(matrix)

2.7129319932501073

In [25]:
np.std(matrix, 1)

array([1.356466  , 1.16619038])

## ``ndarray.T``

Este parámetro almacena la matriz traspuesta del ``ndarray``.

In [27]:
print(matrix)
matrix.T

[[ 1  3  4  4  5]
 [ 7  7  8  9 10]]


array([[ 1,  7],
       [ 3,  7],
       [ 4,  8],
       [ 4,  9],
       [ 5, 10]])

## ``np.concatenate(arrays, axis)``

Esta función va a concatenar la cantidad de arrays indicados por el eje indicado. Los arrays a concatenar deben tener la misma dimensión y forma (shape).

In [30]:
matrix_1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
matrix_2 = np.array([[2, 4, 5, 7], [9, 4, 1, 0]])
np.concatenate((matrix_1, matrix_2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 5, 7],
       [9, 4, 1, 0]])

Si intentamos concatenar dos listas que no tienen la misma dimensión y forma, obtendremos un error:

In [29]:
try:
    concatenated_array = np.concatenate((matrix, arr), axis=0)
    print(concatenated_array)
except ValueError as error:
    print("Error:", error)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Esto se puede solucionar cambiando la dimensión y forma de los arrays hasta que sean compatibles.

In [31]:
print("Matrix dims:", matrix.ndim)
print("Matrix shape:", matrix.shape)
print("arr dims:", arr.ndim)
print("arr shape:", arr.shape)

Matrix dims: 2
Matrix shape: (2, 5)
arr dims: 1
arr shape: (10,)


In [36]:
reshaped_arr = np.expand_dims(arr, axis=0)
reshaped_arr = reshaped_arr.reshape((2, 5))
concatenated_array = np.concatenate((matrix, reshaped_arr), axis=0)
print(concatenated_array)

[[ 1  3  4  4  5]
 [ 7  7  8  9 10]
 [ 1  3  4  4  5]
 [ 7  7  8  9 10]]


In [38]:
concatenated_array = np.concatenate((matrix, reshaped_arr), axis=1)
print(concatenated_array)

[[ 1  3  4  4  5  1  3  4  4  5]
 [ 7  7  8  9 10  7  7  8  9 10]]
